version: '3'

services:
  ssh_server:
    image: tobapramudia/ssh_server
    environment:
      - SYSLOG_SERVER=alpha_client
    networks:
      - alpha_net
    privileged: true
    build:
      context: ./DemoNode/ssh_server_syslog
  ssh_client:
    image: tobapramudia/ssh_client
    environment:
      - SSH_SERVER=ssh_server
    networks:
      - alpha_net
    privileged: true
    build:
      context: ./DemoNode/ssh_client
networks:
  alpha_net:
    external: true